// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: audit/controlpb/control.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BigQueryControlEvent struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	Uuid                             *string                `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Timestamp                        *int64                 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Criticity                        *string                `protobuf:"bytes,3,opt,name=criticity" json:"criticity,omitempty"`
	ControlType                      *string                `protobuf:"bytes,4,opt,name=control_type,json=controlType" json:"control_type,omitempty"`
	InternalCode                     *string                `protobuf:"bytes,5,opt,name=internal_code,json=internalCode" json:"internal_code,omitempty"`
	TargetModelClass                 *string                `protobuf:"bytes,6,opt,name=target_model_class,json=targetModelClass" json:"target_model_class,omitempty"`
	TargetModelUuid                  *string                `protobuf:"bytes,7,opt,name=target_model_uuid,json=targetModelUuid" json:"target_model_uuid,omitempty"`
	TranslationInfoMessageKey        *string                `protobuf:"bytes,8,opt,name=translation_info_message_key,json=translationInfoMessageKey" json:"translation_info_message_key,omitempty"`
	TranslationInfoMessageAttributes *string                `protobuf:"bytes,9,opt,name=translation_info_message_attributes,json=translationInfoMessageAttributes" json:"translation_info_message_attributes,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *BigQueryControlEvent) Reset() {
	*x = BigQueryControlEvent{}
	mi := &file_audit_controlpb_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BigQueryControlEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BigQueryControlEvent) ProtoMessage() {}

func (x *BigQueryControlEvent) ProtoReflect() protoreflect.Message {
	mi := &file_audit_controlpb_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BigQueryControlEvent.ProtoReflect.Descriptor instead.
func (*BigQueryControlEvent) Descriptor() ([]byte, []int) {
	return file_audit_controlpb_control_proto_rawDescGZIP(), []int{0}
}

func (x *BigQueryControlEvent) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *BigQueryControlEvent) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *BigQueryControlEvent) GetCriticity() string {
	if x != nil && x.Criticity != nil {
		return *x.Criticity
	}
	return ""
}

func (x *BigQueryControlEvent) GetControlType() string {
	if x != nil && x.ControlType != nil {
		return *x.ControlType
	}
	return ""
}

func (x *BigQueryControlEvent) GetInternalCode() string {
	if x != nil && x.InternalCode != nil {
		return *x.InternalCode
	}
	return ""
}

func (x *BigQueryControlEvent) GetTargetModelClass() string {
	if x != nil && x.TargetModelClass != nil {
		return *x.TargetModelClass
	}
	return ""
}

func (x *BigQueryControlEvent) GetTargetModelUuid() string {
	if x != nil && x.TargetModelUuid != nil {
		return *x.TargetModelUuid
	}
	return ""
}

func (x *BigQueryControlEvent) GetTranslationInfoMessageKey() string {
	if x != nil && x.TranslationInfoMessageKey != nil {
		return *x.TranslationInfoMessageKey
	}
	return ""
}

func (x *BigQueryControlEvent) GetTranslationInfoMessageAttributes() string {
	if x != nil && x.TranslationInfoMessageAttributes != nil {
		return *x.TranslationInfoMessageAttributes
	}
	return ""
}

var File_audit_controlpb_control_proto protoreflect.FileDescriptor

const file_audit_controlpb_control_proto_rawDesc = "" +
	"\n" +
	"\x1daudit/controlpb/control.proto\x12\tcontrolpb\"\x98\x03\n" +
	"\x14BigQueryControlEvent\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tcriticity\x18\x03 \x01(\tR\tcriticity\x12!\n" +
	"\fcontrol_type\x18\x04 \x01(\tR\vcontrolType\x12#\n" +
	"\rinternal_code\x18\x05 \x01(\tR\finternalCode\x12,\n" +
	"\x12target_model_class\x18\x06 \x01(\tR\x10targetModelClass\x12*\n" +
	"\x11target_model_uuid\x18\a \x01(\tR\x0ftargetModelUuid\x12?\n" +
	"\x1ctranslation_info_message_key\x18\b \x01(\tR\x19translationInfoMessageKey\x12M\n" +
	"#translation_info_message_attributes\x18\t \x01(\tR translationInfoMessageAttributesB0Z.bitbucket.org/enroute-mobi/ara/audit/controlpb"

var (
	file_audit_controlpb_control_proto_rawDescOnce sync.Once
	file_audit_controlpb_control_proto_rawDescData []byte
)

func file_audit_controlpb_control_proto_rawDescGZIP() []byte {
	file_audit_controlpb_control_proto_rawDescOnce.Do(func() {
		file_audit_controlpb_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_controlpb_control_proto_rawDesc), len(file_audit_controlpb_control_proto_rawDesc)))
	})
	return file_audit_controlpb_control_proto_rawDescData
}

var file_audit_controlpb_control_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_audit_controlpb_control_proto_goTypes = []any{
	(*BigQueryControlEvent)(nil), // 0: controlpb.BigQueryControlEvent
}
var file_audit_controlpb_control_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_audit_controlpb_control_proto_init() }
func file_audit_controlpb_control_proto_init() {
	if File_audit_controlpb_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_controlpb_control_proto_rawDesc), len(file_audit_controlpb_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_audit_controlpb_control_proto_goTypes,
		DependencyIndexes: file_audit_controlpb_control_proto_depIdxs,
		MessageInfos:      file_audit_controlpb_control_proto_msgTypes,
	}.Build()
	File_audit_controlpb_control_proto = out.File
	file_audit_controlpb_control_proto_goTypes = nil
	file_audit_controlpb_control_proto_depIdxs = nil
}
