# docker build -t edwig-build -f Dockerfile.debian .
# docker run -v $PWD/target:/target edwig-build

# ARG DEBIAN_VERSION=jessie
FROM debian:jessie-slim

ARG WEEK

RUN apt-get update && apt-get -y dist-upgrade && \
    apt-get install -y --no-install-recommends devscripts fakeroot equivs && \
    mkdir /build

WORKDIR /build
COPY . /build

ENV DEBIAN_FRONTEND=noninteractive

ENV GOLANG_VERSION=1.12.7
ENV BUILD_NUMBER=""

VOLUME /target
CMD ["./build-debian.sh", "/target"]
