package siri_attributes

const (
	Address                                = "Address"
	MessageIdentifier                      = "MessageIdentifier"
	ProducerRef                            = "ProducerRef"
	ResponseMessageIdentifier              = "ResponseMessageIdentifier"
	RequestTimestamp                       = "RequestTimestamp"
	ServiceStartedTime                     = "ServiceStartedTime"
	TerminationResponseStatus              = "TerminationResponseStatus"
	EstimatedVehicleJourney                = "EstimatedVehicleJourney"
	EstimatedCall                          = "EstimatedCall"
	RecordedCall                           = "RecordedCall"
	GeneralMessage                         = "GeneralMessage"
	LineSection                            = "LineSection"
	Message                                = "Message"
	AnnotatedLineRef                       = "AnnotatedLineRef"
	EstimatedTimetableDelivery             = "EstimatedTimetableDelivery"
	EstimatedJourneyVersionFrame           = "EstimatedJourneyVersionFrame"
	GeneralMessageDelivery                 = "GeneralMessageDelivery"
	GeneralMessageCancellation             = "GeneralMessageCancellation"
	SituationExchangeDelivery              = "SituationExchangeDelivery"
	StopMonitoringDelivery                 = "StopMonitoringDelivery"
	MonitoredStopVisit                     = "MonitoredStopVisit"
	MonitoredStopVisitCancellation         = "MonitoredStopVisitCancellation"
	VehicleMonitoringDelivery              = "VehicleMonitoringDelivery"
	VehicleActivity                        = "VehicleActivity"
	StopMonitoringRequest                  = "StopMonitoringRequest"
	GeneralMessageRequest                  = "GeneralMessageRequest"
	EstimatedTimetableRequest              = "EstimatedTimetableRequest"
	PtSituationElement                     = "PtSituationElement"
	StopMonitoringSubscriptionRequest      = "StopMonitoringSubscriptionRequest"
	EstimatedTimetableSubscriptionRequest  = "EstimatedTimetableSubscriptionRequest"
	VehicleMonitoringSubscriptionRequest   = "VehicleMonitoringSubscriptionRequest"
	ProductionTimetableSubscriptionRequest = "ProductionTimetableSubscriptionRequest"
	GeneralMessageSubscriptionRequest      = "GeneralMessageSubscriptionRequest"
	SituationExchangeSubscriptionRequest   = "SituationExchangeSubscriptionRequest"
	ResponseStatus                         = "ResponseStatus"
)
