package siri_attributes

const (
	DataFrameRef           = "DataFrameRef"
	DatedVehicleJourneyRef = "DatedVehicleJourneyRef"
	DestinationRef         = "DestinationRef"
	DirectionRef           = "DirectionRef"
	DriverRef              = "DriverRef"
	FacilityRef            = "FacilityRef"
	FacilityStatus         = "FacilityStatus"
	FirstStopPointRef      = "FirstStopPointRef"
	InfoChannelRef         = "InfoChannelRef"
	ItemRef                = "ItemRef"
	JourneyPatternRef      = "JourneyPatternRef"
	LastStopPointRef       = "LastStopPointRef"
	LineRef                = "LineRef"
	MonitoringRef          = "MonitoringRef"
	OperatorRef            = "OperatorRef"
	OriginRef              = "OriginRef"
	ParticipantRef         = "ParticipantRef"
	PlaceRef               = "PlaceRef"
	ProductCategoryRef     = "ProductCategoryRef"
	RequestMessageRef      = "RequestMessageRef"
	RequestorRef           = "RequestorRef"
	ResponderRef           = "ResponderRef"
	RouteRef               = "RouteRef"
	ServiceFeatureRef      = "ServiceFeatureRef"
	SituationRef           = "SituationRef"
	StopPointRef           = "StopPointRef"
	SubscriberRef          = "SubscriberRef"
	SubscriptionRef        = "SubscriptionRef"
	TrainNumberRef         = "TrainNumberRef"
	VehicleFeatureRef      = "VehicleFeatureRef"
	VehicleMonitoringRef   = "VehicleMonitoringRef"
	VehicleRef             = "VehicleRef"
	StopPlaceRef           = "StopPlaceRef"
	AnnotatedStopPointRef  = "AnnotatedStopPointRef"
)
