// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: audit/exchangepb/exchange.proto

package exchangepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BigQueryMessage struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Uuid                    *string                `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Timestamp               *int64                 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	IpAddress               *string                `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress" json:"ip_address,omitempty"`
	Protocol                *string                `protobuf:"bytes,4,opt,name=protocol" json:"protocol,omitempty"`
	Type                    *string                `protobuf:"bytes,5,opt,name=type" json:"type,omitempty"`
	Direction               *string                `protobuf:"bytes,6,opt,name=direction" json:"direction,omitempty"`
	Partner                 *string                `protobuf:"bytes,7,opt,name=partner" json:"partner,omitempty"`
	Status                  *string                `protobuf:"bytes,8,opt,name=status" json:"status,omitempty"`
	ErrorDetails            *string                `protobuf:"bytes,9,opt,name=error_details,json=errorDetails" json:"error_details,omitempty"`
	RequestRawMessage       *string                `protobuf:"bytes,10,opt,name=request_raw_message,json=requestRawMessage" json:"request_raw_message,omitempty"`
	ResponseRawMessage      *string                `protobuf:"bytes,11,opt,name=response_raw_message,json=responseRawMessage" json:"response_raw_message,omitempty"`
	RequestIdentifier       *string                `protobuf:"bytes,12,opt,name=request_identifier,json=requestIdentifier" json:"request_identifier,omitempty"`
	ResponseIdentifier      *string                `protobuf:"bytes,13,opt,name=response_identifier,json=responseIdentifier" json:"response_identifier,omitempty"`
	RequestSize             *int64                 `protobuf:"varint,14,opt,name=request_size,json=requestSize" json:"request_size,omitempty"`
	ResponseSize            *int64                 `protobuf:"varint,15,opt,name=response_size,json=responseSize" json:"response_size,omitempty"`
	ProcessingTime          *float64               `protobuf:"fixed64,16,opt,name=processing_time,json=processingTime" json:"processing_time,omitempty"`
	SubscriptionIdentifiers []string               `protobuf:"bytes,17,rep,name=subscription_identifiers,json=subscriptionIdentifiers" json:"subscription_identifiers,omitempty"`
	Lines                   []string               `protobuf:"bytes,18,rep,name=lines" json:"lines,omitempty"`
	StopAreas               []string               `protobuf:"bytes,19,rep,name=stop_areas,json=stopAreas" json:"stop_areas,omitempty"`
	Vehicles                []string               `protobuf:"bytes,20,rep,name=vehicles" json:"vehicles,omitempty"`
	VehicleJourneys         []string               `protobuf:"bytes,21,rep,name=vehicle_journeys,json=vehicleJourneys" json:"vehicle_journeys,omitempty"`
	Facilities              []string               `protobuf:"bytes,22,rep,name=facilities" json:"facilities,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *BigQueryMessage) Reset() {
	*x = BigQueryMessage{}
	mi := &file_audit_exchangepb_exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BigQueryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BigQueryMessage) ProtoMessage() {}

func (x *BigQueryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_audit_exchangepb_exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BigQueryMessage.ProtoReflect.Descriptor instead.
func (*BigQueryMessage) Descriptor() ([]byte, []int) {
	return file_audit_exchangepb_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *BigQueryMessage) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *BigQueryMessage) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *BigQueryMessage) GetIpAddress() string {
	if x != nil && x.IpAddress != nil {
		return *x.IpAddress
	}
	return ""
}

func (x *BigQueryMessage) GetProtocol() string {
	if x != nil && x.Protocol != nil {
		return *x.Protocol
	}
	return ""
}

func (x *BigQueryMessage) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *BigQueryMessage) GetDirection() string {
	if x != nil && x.Direction != nil {
		return *x.Direction
	}
	return ""
}

func (x *BigQueryMessage) GetPartner() string {
	if x != nil && x.Partner != nil {
		return *x.Partner
	}
	return ""
}

func (x *BigQueryMessage) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *BigQueryMessage) GetErrorDetails() string {
	if x != nil && x.ErrorDetails != nil {
		return *x.ErrorDetails
	}
	return ""
}

func (x *BigQueryMessage) GetRequestRawMessage() string {
	if x != nil && x.RequestRawMessage != nil {
		return *x.RequestRawMessage
	}
	return ""
}

func (x *BigQueryMessage) GetResponseRawMessage() string {
	if x != nil && x.ResponseRawMessage != nil {
		return *x.ResponseRawMessage
	}
	return ""
}

func (x *BigQueryMessage) GetRequestIdentifier() string {
	if x != nil && x.RequestIdentifier != nil {
		return *x.RequestIdentifier
	}
	return ""
}

func (x *BigQueryMessage) GetResponseIdentifier() string {
	if x != nil && x.ResponseIdentifier != nil {
		return *x.ResponseIdentifier
	}
	return ""
}

func (x *BigQueryMessage) GetRequestSize() int64 {
	if x != nil && x.RequestSize != nil {
		return *x.RequestSize
	}
	return 0
}

func (x *BigQueryMessage) GetResponseSize() int64 {
	if x != nil && x.ResponseSize != nil {
		return *x.ResponseSize
	}
	return 0
}

func (x *BigQueryMessage) GetProcessingTime() float64 {
	if x != nil && x.ProcessingTime != nil {
		return *x.ProcessingTime
	}
	return 0
}

func (x *BigQueryMessage) GetSubscriptionIdentifiers() []string {
	if x != nil {
		return x.SubscriptionIdentifiers
	}
	return nil
}

func (x *BigQueryMessage) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *BigQueryMessage) GetStopAreas() []string {
	if x != nil {
		return x.StopAreas
	}
	return nil
}

func (x *BigQueryMessage) GetVehicles() []string {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

func (x *BigQueryMessage) GetVehicleJourneys() []string {
	if x != nil {
		return x.VehicleJourneys
	}
	return nil
}

func (x *BigQueryMessage) GetFacilities() []string {
	if x != nil {
		return x.Facilities
	}
	return nil
}

var File_audit_exchangepb_exchange_proto protoreflect.FileDescriptor

const file_audit_exchangepb_exchange_proto_rawDesc = "" +
	"\n" +
	"\x1faudit/exchangepb/exchange.proto\x12\n" +
	"exchangepb\"\x91\x06\n" +
	"\x0fBigQueryMessage\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1c\n" +
	"\tdirection\x18\x06 \x01(\tR\tdirection\x12\x18\n" +
	"\apartner\x18\a \x01(\tR\apartner\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12#\n" +
	"\rerror_details\x18\t \x01(\tR\ferrorDetails\x12.\n" +
	"\x13request_raw_message\x18\n" +
	" \x01(\tR\x11requestRawMessage\x120\n" +
	"\x14response_raw_message\x18\v \x01(\tR\x12responseRawMessage\x12-\n" +
	"\x12request_identifier\x18\f \x01(\tR\x11requestIdentifier\x12/\n" +
	"\x13response_identifier\x18\r \x01(\tR\x12responseIdentifier\x12!\n" +
	"\frequest_size\x18\x0e \x01(\x03R\vrequestSize\x12#\n" +
	"\rresponse_size\x18\x0f \x01(\x03R\fresponseSize\x12'\n" +
	"\x0fprocessing_time\x18\x10 \x01(\x01R\x0eprocessingTime\x129\n" +
	"\x18subscription_identifiers\x18\x11 \x03(\tR\x17subscriptionIdentifiers\x12\x14\n" +
	"\x05lines\x18\x12 \x03(\tR\x05lines\x12\x1d\n" +
	"\n" +
	"stop_areas\x18\x13 \x03(\tR\tstopAreas\x12\x1a\n" +
	"\bvehicles\x18\x14 \x03(\tR\bvehicles\x12)\n" +
	"\x10vehicle_journeys\x18\x15 \x03(\tR\x0fvehicleJourneys\x12\x1e\n" +
	"\n" +
	"facilities\x18\x16 \x03(\tR\n" +
	"facilitiesB1Z/bitbucket.org/enroute-mobi/ara/audit/exchangepb"

var (
	file_audit_exchangepb_exchange_proto_rawDescOnce sync.Once
	file_audit_exchangepb_exchange_proto_rawDescData []byte
)

func file_audit_exchangepb_exchange_proto_rawDescGZIP() []byte {
	file_audit_exchangepb_exchange_proto_rawDescOnce.Do(func() {
		file_audit_exchangepb_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_exchangepb_exchange_proto_rawDesc), len(file_audit_exchangepb_exchange_proto_rawDesc)))
	})
	return file_audit_exchangepb_exchange_proto_rawDescData
}

var file_audit_exchangepb_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_audit_exchangepb_exchange_proto_goTypes = []any{
	(*BigQueryMessage)(nil), // 0: exchangepb.BigQueryMessage
}
var file_audit_exchangepb_exchange_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_audit_exchangepb_exchange_proto_init() }
func file_audit_exchangepb_exchange_proto_init() {
	if File_audit_exchangepb_exchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_exchangepb_exchange_proto_rawDesc), len(file_audit_exchangepb_exchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_audit_exchangepb_exchange_proto_goTypes,
		DependencyIndexes: file_audit_exchangepb_exchange_proto_depIdxs,
		MessageInfos:      file_audit_exchangepb_exchange_proto_msgTypes,
	}.Build()
	File_audit_exchangepb_exchange_proto = out.File
	file_audit_exchangepb_exchange_proto_goTypes = nil
	file_audit_exchangepb_exchange_proto_depIdxs = nil
}
