// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: audit/longtermsvpb/longtermsv.proto

package longtermsvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CodeSpace     *string                `protobuf:"bytes,1,opt,name=code_space,json=codeSpace" json:"code_space,omitempty"`
	Value         *string                `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Code) Reset() {
	*x = Code{}
	mi := &file_audit_longtermsvpb_longtermsv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Code) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Code) ProtoMessage() {}

func (x *Code) ProtoReflect() protoreflect.Message {
	mi := &file_audit_longtermsvpb_longtermsv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Code.ProtoReflect.Descriptor instead.
func (*Code) Descriptor() ([]byte, []int) {
	return file_audit_longtermsvpb_longtermsv_proto_rawDescGZIP(), []int{0}
}

func (x *Code) GetCodeSpace() string {
	if x != nil && x.CodeSpace != nil {
		return *x.CodeSpace
	}
	return ""
}

func (x *Code) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type BigQueryLongTermStopVisitEvent struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	Uuid                          *string                `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Timestamp                     *int64                 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	StopVisitUuid                 *string                `protobuf:"bytes,3,opt,name=stop_visit_uuid,json=stopVisitUuid" json:"stop_visit_uuid,omitempty"`
	PassageOrder                  *string                `protobuf:"bytes,4,opt,name=passage_order,json=passageOrder" json:"passage_order,omitempty"`
	AimedDepartureTime            *int64                 `protobuf:"varint,5,opt,name=aimed_departure_time,json=aimedDepartureTime" json:"aimed_departure_time,omitempty"`
	AimedArrivalTime              *int64                 `protobuf:"varint,6,opt,name=aimed_arrival_time,json=aimedArrivalTime" json:"aimed_arrival_time,omitempty"`
	ExpectedDepartureTime         *int64                 `protobuf:"varint,7,opt,name=expected_departure_time,json=expectedDepartureTime" json:"expected_departure_time,omitempty"`
	ExpectedArrivalTime           *int64                 `protobuf:"varint,8,opt,name=expected_arrival_time,json=expectedArrivalTime" json:"expected_arrival_time,omitempty"`
	ActualDepartureTime           *int64                 `protobuf:"varint,9,opt,name=actual_departure_time,json=actualDepartureTime" json:"actual_departure_time,omitempty"`
	ActualArrivalTime             *int64                 `protobuf:"varint,10,opt,name=actual_arrival_time,json=actualArrivalTime" json:"actual_arrival_time,omitempty"`
	DepartureStatus               *string                `protobuf:"bytes,11,opt,name=departure_status,json=departureStatus" json:"departure_status,omitempty"`
	ArrivalStatus                 *string                `protobuf:"bytes,12,opt,name=arrival_status,json=arrivalStatus" json:"arrival_status,omitempty"`
	StopAreaName                  *string                `protobuf:"bytes,13,opt,name=stop_area_name,json=stopAreaName" json:"stop_area_name,omitempty"`
	StopAreaCodes                 []*Code                `protobuf:"bytes,14,rep,name=stop_area_codes,json=stopAreaCodes" json:"stop_area_codes,omitempty"`
	StopAreaCoordinates           *string                `protobuf:"bytes,15,opt,name=stop_area_coordinates,json=stopAreaCoordinates" json:"stop_area_coordinates,omitempty"`
	LineName                      *string                `protobuf:"bytes,16,opt,name=line_name,json=lineName" json:"line_name,omitempty"`
	LineNumber                    *string                `protobuf:"bytes,17,opt,name=line_number,json=lineNumber" json:"line_number,omitempty"`
	TransportMode                 *string                `protobuf:"bytes,18,opt,name=transport_mode,json=transportMode" json:"transport_mode,omitempty"`
	LineCodes                     []*Code                `protobuf:"bytes,19,rep,name=line_codes,json=lineCodes" json:"line_codes,omitempty"`
	VehicleJourneyDirectionType   *string                `protobuf:"bytes,20,opt,name=vehicle_journey_direction_type,json=vehicleJourneyDirectionType" json:"vehicle_journey_direction_type,omitempty"`
	VehicleJourneyOriginName      *string                `protobuf:"bytes,21,opt,name=vehicle_journey_origin_name,json=vehicleJourneyOriginName" json:"vehicle_journey_origin_name,omitempty"`
	VehicleJourneyDestinationName *string                `protobuf:"bytes,22,opt,name=vehicle_journey_destination_name,json=vehicleJourneyDestinationName" json:"vehicle_journey_destination_name,omitempty"`
	VehicleJourneyCodes           []*Code                `protobuf:"bytes,23,rep,name=vehicle_journey_codes,json=vehicleJourneyCodes" json:"vehicle_journey_codes,omitempty"`
	VehicleDriverRef              *string                `protobuf:"bytes,24,opt,name=vehicle_driver_ref,json=vehicleDriverRef" json:"vehicle_driver_ref,omitempty"`
	VehicleOccupancy              *string                `protobuf:"bytes,25,opt,name=vehicle_occupancy,json=vehicleOccupancy" json:"vehicle_occupancy,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *BigQueryLongTermStopVisitEvent) Reset() {
	*x = BigQueryLongTermStopVisitEvent{}
	mi := &file_audit_longtermsvpb_longtermsv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BigQueryLongTermStopVisitEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BigQueryLongTermStopVisitEvent) ProtoMessage() {}

func (x *BigQueryLongTermStopVisitEvent) ProtoReflect() protoreflect.Message {
	mi := &file_audit_longtermsvpb_longtermsv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BigQueryLongTermStopVisitEvent.ProtoReflect.Descriptor instead.
func (*BigQueryLongTermStopVisitEvent) Descriptor() ([]byte, []int) {
	return file_audit_longtermsvpb_longtermsv_proto_rawDescGZIP(), []int{1}
}

func (x *BigQueryLongTermStopVisitEvent) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *BigQueryLongTermStopVisitEvent) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *BigQueryLongTermStopVisitEvent) GetStopVisitUuid() string {
	if x != nil && x.StopVisitUuid != nil {
		return *x.StopVisitUuid
	}
	return ""
}

func (x *BigQueryLongTermStopVisitEvent) GetPassageOrder() string {
	if x != nil && x.PassageOrder != nil {
		return *x.PassageOrder
	}
	return ""
}

func (x *BigQueryLongTermStopVisitEvent) GetAimedDepartureTime() int64 {
	if x != nil && x.AimedDepartureTime != nil {
		return *x.AimedDepartureTime
	}
	return 0
}

func (x *BigQueryLongTermStopVisitEvent) GetAimedArrivalTime() int64 {
	if x != nil && x.AimedArrivalTime != nil {
		return *x.AimedArrivalTime
	}
	return 0
}

func (x *BigQueryLongTermStopVisitEvent) GetExpectedDepartureTime() int64 {
	if x != nil && x.ExpectedDepartureTime != nil {
		return *x.ExpectedDepartureTime
	}
	return 0
}

func (x *BigQueryLongTermStopVisitEvent) GetExpectedArrivalTime() int64 {
	if x != nil && x.ExpectedArrivalTime != nil {
		return *x.ExpectedArrivalTime
	}
	return 0
}

func (x *BigQueryLongTermStopVisitEvent) GetActualDepartureTime() int64 {
	if x != nil && x.ActualDepartureTime != nil {
		return *x.ActualDepartureTime
	}
	return 0
}

func (x *BigQueryLongTermStopVisitEvent) GetActualArrivalTime() int64 {
	if x != nil && x.ActualArrivalTime != nil {
		return *x.ActualArrivalTime
	}
	return 0
}

func (x *BigQueryLongTermStopVisitEvent) GetDepartureStatus() string {
	if x != nil && x.DepartureStatus != nil {
		return *x.DepartureStatus
	}
	return ""
}

func (x *BigQueryLongTermStopVisitEvent) GetArrivalStatus() string {
	if x != nil && x.ArrivalStatus != nil {
		return *x.ArrivalStatus
	}
	return ""
}

func (x *BigQueryLongTermStopVisitEvent) GetStopAreaName() string {
	if x != nil && x.StopAreaName != nil {
		return *x.StopAreaName
	}
	return ""
}

func (x *BigQueryLongTermStopVisitEvent) GetStopAreaCodes() []*Code {
	if x != nil {
		return x.StopAreaCodes
	}
	return nil
}

func (x *BigQueryLongTermStopVisitEvent) GetStopAreaCoordinates() string {
	if x != nil && x.StopAreaCoordinates != nil {
		return *x.StopAreaCoordinates
	}
	return ""
}

func (x *BigQueryLongTermStopVisitEvent) GetLineName() string {
	if x != nil && x.LineName != nil {
		return *x.LineName
	}
	return ""
}

func (x *BigQueryLongTermStopVisitEvent) GetLineNumber() string {
	if x != nil && x.LineNumber != nil {
		return *x.LineNumber
	}
	return ""
}

func (x *BigQueryLongTermStopVisitEvent) GetTransportMode() string {
	if x != nil && x.TransportMode != nil {
		return *x.TransportMode
	}
	return ""
}

func (x *BigQueryLongTermStopVisitEvent) GetLineCodes() []*Code {
	if x != nil {
		return x.LineCodes
	}
	return nil
}

func (x *BigQueryLongTermStopVisitEvent) GetVehicleJourneyDirectionType() string {
	if x != nil && x.VehicleJourneyDirectionType != nil {
		return *x.VehicleJourneyDirectionType
	}
	return ""
}

func (x *BigQueryLongTermStopVisitEvent) GetVehicleJourneyOriginName() string {
	if x != nil && x.VehicleJourneyOriginName != nil {
		return *x.VehicleJourneyOriginName
	}
	return ""
}

func (x *BigQueryLongTermStopVisitEvent) GetVehicleJourneyDestinationName() string {
	if x != nil && x.VehicleJourneyDestinationName != nil {
		return *x.VehicleJourneyDestinationName
	}
	return ""
}

func (x *BigQueryLongTermStopVisitEvent) GetVehicleJourneyCodes() []*Code {
	if x != nil {
		return x.VehicleJourneyCodes
	}
	return nil
}

func (x *BigQueryLongTermStopVisitEvent) GetVehicleDriverRef() string {
	if x != nil && x.VehicleDriverRef != nil {
		return *x.VehicleDriverRef
	}
	return ""
}

func (x *BigQueryLongTermStopVisitEvent) GetVehicleOccupancy() string {
	if x != nil && x.VehicleOccupancy != nil {
		return *x.VehicleOccupancy
	}
	return ""
}

var File_audit_longtermsvpb_longtermsv_proto protoreflect.FileDescriptor

const file_audit_longtermsvpb_longtermsv_proto_rawDesc = "" +
	"\n" +
	"#audit/longtermsvpb/longtermsv.proto\x12\flongtermsvpb\";\n" +
	"\x04Code\x12\x1d\n" +
	"\n" +
	"code_space\x18\x01 \x01(\tR\tcodeSpace\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xbf\t\n" +
	"\x1eBigQueryLongTermStopVisitEvent\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12&\n" +
	"\x0fstop_visit_uuid\x18\x03 \x01(\tR\rstopVisitUuid\x12#\n" +
	"\rpassage_order\x18\x04 \x01(\tR\fpassageOrder\x120\n" +
	"\x14aimed_departure_time\x18\x05 \x01(\x03R\x12aimedDepartureTime\x12,\n" +
	"\x12aimed_arrival_time\x18\x06 \x01(\x03R\x10aimedArrivalTime\x126\n" +
	"\x17expected_departure_time\x18\a \x01(\x03R\x15expectedDepartureTime\x122\n" +
	"\x15expected_arrival_time\x18\b \x01(\x03R\x13expectedArrivalTime\x122\n" +
	"\x15actual_departure_time\x18\t \x01(\x03R\x13actualDepartureTime\x12.\n" +
	"\x13actual_arrival_time\x18\n" +
	" \x01(\x03R\x11actualArrivalTime\x12)\n" +
	"\x10departure_status\x18\v \x01(\tR\x0fdepartureStatus\x12%\n" +
	"\x0earrival_status\x18\f \x01(\tR\rarrivalStatus\x12$\n" +
	"\x0estop_area_name\x18\r \x01(\tR\fstopAreaName\x12:\n" +
	"\x0fstop_area_codes\x18\x0e \x03(\v2\x12.longtermsvpb.CodeR\rstopAreaCodes\x122\n" +
	"\x15stop_area_coordinates\x18\x0f \x01(\tR\x13stopAreaCoordinates\x12\x1b\n" +
	"\tline_name\x18\x10 \x01(\tR\blineName\x12\x1f\n" +
	"\vline_number\x18\x11 \x01(\tR\n" +
	"lineNumber\x12%\n" +
	"\x0etransport_mode\x18\x12 \x01(\tR\rtransportMode\x121\n" +
	"\n" +
	"line_codes\x18\x13 \x03(\v2\x12.longtermsvpb.CodeR\tlineCodes\x12C\n" +
	"\x1evehicle_journey_direction_type\x18\x14 \x01(\tR\x1bvehicleJourneyDirectionType\x12=\n" +
	"\x1bvehicle_journey_origin_name\x18\x15 \x01(\tR\x18vehicleJourneyOriginName\x12G\n" +
	" vehicle_journey_destination_name\x18\x16 \x01(\tR\x1dvehicleJourneyDestinationName\x12F\n" +
	"\x15vehicle_journey_codes\x18\x17 \x03(\v2\x12.longtermsvpb.CodeR\x13vehicleJourneyCodes\x12,\n" +
	"\x12vehicle_driver_ref\x18\x18 \x01(\tR\x10vehicleDriverRef\x12+\n" +
	"\x11vehicle_occupancy\x18\x19 \x01(\tR\x10vehicleOccupancyB3Z1bitbucket.org/enroute-mobi/ara/audit/longtermsvpb"

var (
	file_audit_longtermsvpb_longtermsv_proto_rawDescOnce sync.Once
	file_audit_longtermsvpb_longtermsv_proto_rawDescData []byte
)

func file_audit_longtermsvpb_longtermsv_proto_rawDescGZIP() []byte {
	file_audit_longtermsvpb_longtermsv_proto_rawDescOnce.Do(func() {
		file_audit_longtermsvpb_longtermsv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_longtermsvpb_longtermsv_proto_rawDesc), len(file_audit_longtermsvpb_longtermsv_proto_rawDesc)))
	})
	return file_audit_longtermsvpb_longtermsv_proto_rawDescData
}

var file_audit_longtermsvpb_longtermsv_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_audit_longtermsvpb_longtermsv_proto_goTypes = []any{
	(*Code)(nil),                           // 0: longtermsvpb.Code
	(*BigQueryLongTermStopVisitEvent)(nil), // 1: longtermsvpb.BigQueryLongTermStopVisitEvent
}
var file_audit_longtermsvpb_longtermsv_proto_depIdxs = []int32{
	0, // 0: longtermsvpb.BigQueryLongTermStopVisitEvent.stop_area_codes:type_name -> longtermsvpb.Code
	0, // 1: longtermsvpb.BigQueryLongTermStopVisitEvent.line_codes:type_name -> longtermsvpb.Code
	0, // 2: longtermsvpb.BigQueryLongTermStopVisitEvent.vehicle_journey_codes:type_name -> longtermsvpb.Code
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_audit_longtermsvpb_longtermsv_proto_init() }
func file_audit_longtermsvpb_longtermsv_proto_init() {
	if File_audit_longtermsvpb_longtermsv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_longtermsvpb_longtermsv_proto_rawDesc), len(file_audit_longtermsvpb_longtermsv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_audit_longtermsvpb_longtermsv_proto_goTypes,
		DependencyIndexes: file_audit_longtermsvpb_longtermsv_proto_depIdxs,
		MessageInfos:      file_audit_longtermsvpb_longtermsv_proto_msgTypes,
	}.Build()
	File_audit_longtermsvpb_longtermsv_proto = out.File
	file_audit_longtermsvpb_longtermsv_proto_goTypes = nil
	file_audit_longtermsvpb_longtermsv_proto_depIdxs = nil
}
