// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: audit/vehiclepb/vehicle.proto

package vehiclepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BigQueryVehicleEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Uuid           *string                `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Timestamp      *int64                 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Id             *string                `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Codes          []string               `protobuf:"bytes,4,rep,name=codes" json:"codes,omitempty"`
	Longitude      *float64               `protobuf:"fixed64,5,opt,name=longitude" json:"longitude,omitempty"`
	Latitude       *float64               `protobuf:"fixed64,6,opt,name=latitude" json:"latitude,omitempty"`
	Bearing        *float64               `protobuf:"fixed64,7,opt,name=bearing" json:"bearing,omitempty"`
	RecordedAtTime *string                `protobuf:"bytes,8,opt,name=recorded_at_time,json=recordedAtTime" json:"recorded_at_time,omitempty"`
	Occupancy      *string                `protobuf:"bytes,9,opt,name=occupancy" json:"occupancy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BigQueryVehicleEvent) Reset() {
	*x = BigQueryVehicleEvent{}
	mi := &file_audit_vehiclepb_vehicle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BigQueryVehicleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BigQueryVehicleEvent) ProtoMessage() {}

func (x *BigQueryVehicleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_audit_vehiclepb_vehicle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BigQueryVehicleEvent.ProtoReflect.Descriptor instead.
func (*BigQueryVehicleEvent) Descriptor() ([]byte, []int) {
	return file_audit_vehiclepb_vehicle_proto_rawDescGZIP(), []int{0}
}

func (x *BigQueryVehicleEvent) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *BigQueryVehicleEvent) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *BigQueryVehicleEvent) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *BigQueryVehicleEvent) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

func (x *BigQueryVehicleEvent) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *BigQueryVehicleEvent) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *BigQueryVehicleEvent) GetBearing() float64 {
	if x != nil && x.Bearing != nil {
		return *x.Bearing
	}
	return 0
}

func (x *BigQueryVehicleEvent) GetRecordedAtTime() string {
	if x != nil && x.RecordedAtTime != nil {
		return *x.RecordedAtTime
	}
	return ""
}

func (x *BigQueryVehicleEvent) GetOccupancy() string {
	if x != nil && x.Occupancy != nil {
		return *x.Occupancy
	}
	return ""
}

var File_audit_vehiclepb_vehicle_proto protoreflect.FileDescriptor

const file_audit_vehiclepb_vehicle_proto_rawDesc = "" +
	"\n" +
	"\x1daudit/vehiclepb/vehicle.proto\x12\tvehiclepb\"\x8a\x02\n" +
	"\x14BigQueryVehicleEvent\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x14\n" +
	"\x05codes\x18\x04 \x03(\tR\x05codes\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\x01R\blatitude\x12\x18\n" +
	"\abearing\x18\a \x01(\x01R\abearing\x12(\n" +
	"\x10recorded_at_time\x18\b \x01(\tR\x0erecordedAtTime\x12\x1c\n" +
	"\toccupancy\x18\t \x01(\tR\toccupancyB0Z.bitbucket.org/enroute-mobi/ara/audit/vehiclepb"

var (
	file_audit_vehiclepb_vehicle_proto_rawDescOnce sync.Once
	file_audit_vehiclepb_vehicle_proto_rawDescData []byte
)

func file_audit_vehiclepb_vehicle_proto_rawDescGZIP() []byte {
	file_audit_vehiclepb_vehicle_proto_rawDescOnce.Do(func() {
		file_audit_vehiclepb_vehicle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_vehiclepb_vehicle_proto_rawDesc), len(file_audit_vehiclepb_vehicle_proto_rawDesc)))
	})
	return file_audit_vehiclepb_vehicle_proto_rawDescData
}

var file_audit_vehiclepb_vehicle_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_audit_vehiclepb_vehicle_proto_goTypes = []any{
	(*BigQueryVehicleEvent)(nil), // 0: vehiclepb.BigQueryVehicleEvent
}
var file_audit_vehiclepb_vehicle_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_audit_vehiclepb_vehicle_proto_init() }
func file_audit_vehiclepb_vehicle_proto_init() {
	if File_audit_vehiclepb_vehicle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_vehiclepb_vehicle_proto_rawDesc), len(file_audit_vehiclepb_vehicle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_audit_vehiclepb_vehicle_proto_goTypes,
		DependencyIndexes: file_audit_vehiclepb_vehicle_proto_depIdxs,
		MessageInfos:      file_audit_vehiclepb_vehicle_proto_msgTypes,
	}.Build()
	File_audit_vehiclepb_vehicle_proto = out.File
	file_audit_vehiclepb_vehicle_proto_goTypes = nil
	file_audit_vehiclepb_vehicle_proto_depIdxs = nil
}
