// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: audit/partnerpb/partner.proto

package partnerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BigQueryPartnerEvent struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Uuid                     *string                `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Timestamp                *int64                 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Slug                     *string                `protobuf:"bytes,3,opt,name=slug" json:"slug,omitempty"`
	PartnerUuid              *string                `protobuf:"bytes,4,opt,name=partner_uuid,json=partnerUuid" json:"partner_uuid,omitempty"`
	PreviousStatus           *string                `protobuf:"bytes,5,opt,name=previous_status,json=previousStatus" json:"previous_status,omitempty"`
	PreviousServiceStartedAt *string                `protobuf:"bytes,6,opt,name=previous_service_started_at,json=previousServiceStartedAt" json:"previous_service_started_at,omitempty"`
	NewStatus                *string                `protobuf:"bytes,7,opt,name=new_status,json=newStatus" json:"new_status,omitempty"`
	NewServiceStartedAt      *string                `protobuf:"bytes,8,opt,name=new_service_started_at,json=newServiceStartedAt" json:"new_service_started_at,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *BigQueryPartnerEvent) Reset() {
	*x = BigQueryPartnerEvent{}
	mi := &file_audit_partnerpb_partner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BigQueryPartnerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BigQueryPartnerEvent) ProtoMessage() {}

func (x *BigQueryPartnerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_audit_partnerpb_partner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BigQueryPartnerEvent.ProtoReflect.Descriptor instead.
func (*BigQueryPartnerEvent) Descriptor() ([]byte, []int) {
	return file_audit_partnerpb_partner_proto_rawDescGZIP(), []int{0}
}

func (x *BigQueryPartnerEvent) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *BigQueryPartnerEvent) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *BigQueryPartnerEvent) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

func (x *BigQueryPartnerEvent) GetPartnerUuid() string {
	if x != nil && x.PartnerUuid != nil {
		return *x.PartnerUuid
	}
	return ""
}

func (x *BigQueryPartnerEvent) GetPreviousStatus() string {
	if x != nil && x.PreviousStatus != nil {
		return *x.PreviousStatus
	}
	return ""
}

func (x *BigQueryPartnerEvent) GetPreviousServiceStartedAt() string {
	if x != nil && x.PreviousServiceStartedAt != nil {
		return *x.PreviousServiceStartedAt
	}
	return ""
}

func (x *BigQueryPartnerEvent) GetNewStatus() string {
	if x != nil && x.NewStatus != nil {
		return *x.NewStatus
	}
	return ""
}

func (x *BigQueryPartnerEvent) GetNewServiceStartedAt() string {
	if x != nil && x.NewServiceStartedAt != nil {
		return *x.NewServiceStartedAt
	}
	return ""
}

var File_audit_partnerpb_partner_proto protoreflect.FileDescriptor

const file_audit_partnerpb_partner_proto_rawDesc = "" +
	"\n" +
	"\x1daudit/partnerpb/partner.proto\x12\tpartnerpb\"\xbb\x02\n" +
	"\x14BigQueryPartnerEvent\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12!\n" +
	"\fpartner_uuid\x18\x04 \x01(\tR\vpartnerUuid\x12'\n" +
	"\x0fprevious_status\x18\x05 \x01(\tR\x0epreviousStatus\x12=\n" +
	"\x1bprevious_service_started_at\x18\x06 \x01(\tR\x18previousServiceStartedAt\x12\x1d\n" +
	"\n" +
	"new_status\x18\a \x01(\tR\tnewStatus\x123\n" +
	"\x16new_service_started_at\x18\b \x01(\tR\x13newServiceStartedAtB0Z.bitbucket.org/enroute-mobi/ara/audit/partnerpb"

var (
	file_audit_partnerpb_partner_proto_rawDescOnce sync.Once
	file_audit_partnerpb_partner_proto_rawDescData []byte
)

func file_audit_partnerpb_partner_proto_rawDescGZIP() []byte {
	file_audit_partnerpb_partner_proto_rawDescOnce.Do(func() {
		file_audit_partnerpb_partner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_partnerpb_partner_proto_rawDesc), len(file_audit_partnerpb_partner_proto_rawDesc)))
	})
	return file_audit_partnerpb_partner_proto_rawDescData
}

var file_audit_partnerpb_partner_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_audit_partnerpb_partner_proto_goTypes = []any{
	(*BigQueryPartnerEvent)(nil), // 0: partnerpb.BigQueryPartnerEvent
}
var file_audit_partnerpb_partner_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_audit_partnerpb_partner_proto_init() }
func file_audit_partnerpb_partner_proto_init() {
	if File_audit_partnerpb_partner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_partnerpb_partner_proto_rawDesc), len(file_audit_partnerpb_partner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_audit_partnerpb_partner_proto_goTypes,
		DependencyIndexes: file_audit_partnerpb_partner_proto_depIdxs,
		MessageInfos:      file_audit_partnerpb_partner_proto_msgTypes,
	}.Build()
	File_audit_partnerpb_partner_proto = out.File
	file_audit_partnerpb_partner_proto_goTypes = nil
	file_audit_partnerpb_partner_proto_depIdxs = nil
}
